disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- nesting
- unused_optional_binding
- vertical_parameter_alignment

force_cast: warning
force_try: error

line_length: 175

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- fastlane
- Frameworks
- ATParseTests
